#include "/Engine/Public/Platform.ush"

Buffer<float4> LocalUpBuffer;
Buffer<int> ResolutionBuffer;
Buffer<float4> AxisABuffer;
Buffer<float4> AxisBBuffer;
RWBuffer<float4> VerticesOutput;
RWBuffer<int> TrianglesOutput;
RWBuffer<float4> VertexNormalsOutput;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MyTerrainComputeShader(
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint GroupIndex : SV_GroupIndex)
{
    // TODO: Your shader code here
}
